spring.data.mongodb.uri=mongodb+srv://ayush:Ayush2005@cluster0.5qljlqz.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true

weather.api.key=e214ce574dd38cfd8e4a9d4e14c93b9f